"""initial_master_schema

Revision ID: 853db8178009
Revises: 
Create Date: 2026-02-26 03:23:10.103901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853db8178009'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('dependency_id', sa.Integer(), nullable=True),
    sa.Column('planned_value', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('predecessor_ids', sa.Text(), server_default='[]', nullable=False),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('percent_complete', sa.Float(), server_default='0.5', nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_type', sa.String(), server_default='Task', nullable=False),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
